version: "3.2"
services:
  db:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - db
volumes:
  mongo:
